=== rinnerfabian/unistuff/4. Semester/Publizieren/Material/xsltBeispieleBook/bookNormalized.dtd
<!ELEMENT book (bookTitle,chapter+,references)>
<!--
<!ATTLIST book xmlns CDATA #FIXED "http://www.in.tum.de/brueggem/demos/">
-->
<!ELEMENT bookTitle (#PCDATA)*>
<!ELEMENT chapter (heading,par*)>
<!ATTLIST chapter id ID #IMPLIED>
<!ELEMENT heading (#PCDATA)*>
<!ELEMENT par (#PCDATA | authorsRef | emph | ref | list | fn)*>
<!ELEMENT authorsRef EMPTY>
<!ATTLIST authorsRef refid IDREF #REQUIRED>
<!ELEMENT emph (#PCDATA | emph)*>
<!ELEMENT ref EMPTY>
<!ATTLIST ref refid IDREF #REQUIRED>
<!ELEMENT list (li)*>
<!ELEMENT li (#PCDATA | emph | list | fn | ref)*>
<!ELEMENT fn (#PCDATA | emph | list | fn | ref)*>
<!ELEMENT references (heading,bookRef*)>
<!ELEMENT bookRef (author*,title,publ,year)>
<!ATTLIST bookRef id ID #IMPLIED>
<!ELEMENT authors (author)+>
<!ELEMENT author (chrName,famName)>
<!ELEMENT chrName (#PCDATA)*>
<!ELEMENT famName (#PCDATA)*>
<!ELEMENT title (#PCDATA)*>
<!ELEMENT publ (#PCDATA)*>
<!ELEMENT year (#PCDATA)*>

=== rinnerfabian/unistuff/Publizieren/Material/xsltBeispieleBook/compBookNormalized.xml
<?xml version="1.0"?>

<!DOCTYPE book SYSTEM "bookNormalized.dtd">

<book>
<bookTitle>Compiler Construction</bookTitle>

<chapter id="scanParseCH">
<heading>Scanning and Parsing</heading>

<par><authorsRef refid="dragonBook"/>
in <emph>their <emph>highly popular</emph>
textbook on compiler construction</emph> <ref refid="dragonBook"/>
introduce
<list><li>scanning and</li>
      <li>parsing</li></list>
as the first two phases in compiler construction.<fn>The other
three phases are <list><li>semantic analysis,</li><li>code
generation, and</li><li>code optimization.</li></list></fn></par>

<par><authorsRef refid="loomBook"/> <ref refid="loomBook"/>
provide the theoretical foundation for scanning and parsing.</par>

<par>In <ref refid="laterPhasesCh"/>
we examine the later phases.</par>
</chapter>

<chapter id="laterPhasesCh">
<heading>The Later Phases</heading>
</chapter>

<references>
<heading>References</heading>

<bookRef id="dragonBook">
<author><chrName>A.V.</chrName><famName>Aho</famName></author>
<author><chrName>R.</chrName><famName>Sethi</famName></author>
<author><chrName>J.D.</chrName><famName>Ullman</famName></author>
<title>Compilers: Principles, Techniques, and Tools</title>
<publ>Addison-Wesley</publ><year>1986</year>
</bookRef>

<bookRef id="loomBook">
<author><chrName>J.E.</chrName><famName>Hopcroft</famName></author>
<author><chrName>J.D.</chrName><famName>Ullman</famName></author>
<title>Introduction to Automata Theory, Languages and Computation</title>
<publ>Addison-Wesley</publ><year>1979</year>
</bookRef>
</references>
</book>
