=== rinnerfabian/unistuff/4. Semester/Publizieren/Material/festMenue/festMenueMitRezeptenHierarchisch.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT festMenue (anlass,gericht+)>

<!ELEMENT anlass (#PCDATA)>

<!ELEMENT gericht (name,rezept)>
<!ATTLIST gericht
  typ CDATA #REQUIRED
  identifikator ID #IMPLIED>

<!ELEMENT name (#PCDATA)>

<!ELEMENT rezept (zutaten,zubereitung)>
<!ATTLIST rezept
  personenZahl CDATA #REQUIRED
  rezeptFuer IDREF #IMPLIED>

<!ELEMENT zutaten (zutat)+>

<!ELEMENT zubereitung (schritt)+>

<!ELEMENT zutat (#PCDATA)>
<!ATTLIST zutat
  einheit CDATA #IMPLIED
  menge CDATA #IMPLIED>

<!ELEMENT schritt (#PCDATA)>

=== rinnerfabian/unistuff/Publizieren/Material/festMenue/gebMenueMitRezeptenHierarchisch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE festMenue SYSTEM "festMenueMitRezeptenHierarchisch.dtd">

<festMenue>
	<anlass>Runder Geburtstag</anlass>
	<gericht typ="Vorspeise">
		<name>Hartgekochtes Ei</name>
		<rezept personenZahl="4">
			<zutaten>
				<zutat menge="4">Eier</zutat>
				<zutat menge="1" einheit="l">Wasser</zutat>
				<zutat menge="4" einheit="TL">Lachsrogen</zutat>
				<zutat menge="4" einheit="Stangen">Schnittlauch</zutat>
			</zutaten>
			<zubereitung>
				<schritt>Das Wasser zum Kochen bringen</schritt>
				<schritt>Die Eier anpieksen</schritt>
				<schritt>Die Eier 5 Minuten lang im Wasser kochen</schritt>
				<schritt>Die Eier abschrecken und abkühlen lassen</schritt>
				<schritt>Die Eier pellen und halbieren</schritt>
				<schritt>Jede Eihälfte mit einem halben TL Lachsrogen und einer halben
					Stange Schnittlauch belegen</schritt>
			</zubereitung>
		</rezept>
	</gericht>
	<gericht typ="Zwischengericht">
		<name>Eiersalat</name>
		<rezept personenZahl="4">
			<zutaten>
				<zutat menge="4">Eier</zutat>
				<zutat menge="2" einheit="EL">Mayonnaise</zutat>
				<zutat menge="3" einheit="EL">Joghurt</zutat>
				<zutat menge="1" einheit="TL">Senf</zutat>
				<zutat>Salz, Piment</zutat>
			</zutaten>
			<zubereitung>
				<schritt>Das Wasser zum Kochen bringen</schritt>
				<schritt>Die Eier anpieksen</schritt>
				<schritt>Die Eier 5 Minuten lang im Wasser kochen</schritt>
				<schritt>Die Eier abschrecken und abkühlen lassen</schritt>
				<schritt>Die Eier pellen und mit dem Eierschneider längs und quer in
					Stücke schneiden</schritt>
				<schritt>Eine Soße aus Mayonnaise, Joghurt und Senf anrühren</schritt>
				<schritt>Die Soße mit Salz und Piment abschmecken</schritt>
				<schritt>Die Eier vorsichtig unter die Soße heben</schritt>
			</zubereitung>
		</rezept>
	</gericht>
	<gericht typ="Hauptgericht">
		<name>Omelett</name>
		<rezept personenZahl="4">
			<zutaten>
				<zutat menge="4">Eier</zutat>
				<zutat menge="2" einheit="EL">Milch</zutat>
				<zutat>Salz</zutat>
				<zutat menge="1">Zwiebel</zutat>
				<zutat menge="1" einheit="Zehe">Knoblauch</zutat>
				<zutat menge="30" einheit="g">Butter</zutat>
				<zutat>Korianderblätter</zutat>
			</zutaten>
			<zubereitung>
				<schritt>Die Eier mit der Milch und etwas Salz verquirlen</schritt>
				<schritt>Die Eier anpieksen</schritt>
				<schritt>Zwiebel und Knoblauch schälen und fein würfeln</schritt>
				<schritt>Die Butter in einer Pfanne schmelzen</schritt>
				<schritt>Zwiebel und Knoblauch in der Butter anbraten, bis sie glasig
					sind</schritt>
				<schritt>Die Eiermischung hinzufügen und langsam stocken
					lassen</schritt>
				<schritt>Die Omeletts mit Korianderblättern verzieren</schritt>
			</zubereitung>
		</rezept>
	</gericht>
	<gericht typ="Nachspeise">
		<name>Kokosmakronen</name>
		<rezept personenZahl="9">
			<zutaten>
				<zutat menge="3">Eiweiß</zutat>
				<zutat menge="210" einheit="g">Puderzucker</zutat>
				<zutat menge="1" einheit="EL">Zitronensaft</zutat>
				<zutat menge="250" einheit="g">Kokosflocken</zutat>
				<zutat menge="0.5" einheit="TL">geriebene Zitronenschale</zutat>
			</zutaten>
			<zubereitung>
				<schritt>Eiweiß sehr steif schlagen</schritt>
				<schritt>Puderzucker und Zitronensaft unterschlagen</schritt>
				<schritt>Kokosflocken und Zitronenschale unterheben</schritt>
				<schritt>Backofen auf 150° vorheizen</schritt>
				<schritt>Den Teig in kleinen Portionen auf ein mit Backpapier
					ausgelegtes Backblech setzen</schritt>
				<schritt>Die Makronen ca. 20 Minuten backen (nicht braun werden
					lassen)</schritt>
			</zubereitung>
		</rezept>
	</gericht>
</festMenue>
