=== rinnerfabian/unistuff/Publizieren/Material/schemaBeispielPeanuts/library.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT book (title,author,character*)>
<!ATTLIST book isbn CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)*>
<!ELEMENT author (#PCDATA)*>
<!ELEMENT name (#PCDATA)*>
<!ELEMENT friend-of (#PCDATA)*>
<!ELEMENT since (#PCDATA)*>
<!ELEMENT qualification (#PCDATA)*>
<!ELEMENT character (name, friend-of*,since,qualification)>

=== rinnerfabian/unistuff/Publizieren/Material/schemaBeispielPeanuts/libraryNamespace.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Nach aktueller Konfigurierung von oXygen wird nicht gemäß DTD validiert,
wenn gleichzeitig ein Schema angegeben ist.
<!DOCTYPE book SYSTEM 'library.dtd'>  
-->
<!--
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="library1.xsd"
-->

<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peanuts.org library3NameSpace.xsd" isbn="0836217462"
	xmlns="http://peanuts.org">
	<title>Being a Dog Is a Full-Time Job</title>
	<author>Charles M. Schulz</author>
	<character>
		<name>Snoopy</name>
		<friend-of>Peppermint Patty</friend-of>
		<since>1950-10-04</since>
		<qualification>extroverted beagle</qualification>
	</character>
	<character>
		<name>Peppermint Patty</name>
		<since>1966-08-22</since>
		<qualification>bold brash tomboyish</qualification>
	</character>
</book>
