=== rinnerfabian/unistuff/4. Semester/Publizieren/Material/schemaBeispielPeanuts/libraryNormalized.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="authorType" mixed="true">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="nickName" type="xsd:string"/>
			<xsd:element name="born" type="xsd:string"/>
			<xsd:element name="dead" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="characterType" mixed="true">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="since" type="xsd:string"/>
			<xsd:element name="qualification" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="bookType">
		<xsd:sequence>
			<xsd:element name="isbn" type="xsd:int"/>
			<xsd:element name="title" type="xsd:string"/>
			<xsd:element name="author" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
			<xsd:element name="character" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="commentsType" mixed="true">
		<xsd:sequence>
			<xsd:element name="characterRef" minOccurs="0" maxOccurs="unbounded">
				<!-- 
				Reference characters within books.
				-->
				<xsd:complexType>
					<xsd:attribute name="book" type="xsd:int" use="required"/>
					<xsd:attribute name="character" type="xsd:string" use="required"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="libraryType">
		<xsd:sequence>
			<xsd:element name="book" type="bookType" minOccurs="0" maxOccurs="unbounded">
				<!-- Innerhalb eines Elements book
					 ist Element author eindeutig durch Textinhalt identifiziert. -->
				<xsd:key name="authorInBookKey">
					<xsd:selector xpath="author"/>
					<xsd:field xpath="."/>
				</xsd:key>
				<!-- Innerhalb eines Elements book
					 ist Element character eindeutig durch Textinhalt identifiziert. -->
				<xsd:key name="characterInBookKey">
					<xsd:selector xpath="character"/>
					<xsd:field xpath="."/>
				</xsd:key>
			</xsd:element>
			<xsd:element name="author" type="authorType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="character" type="characterType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="comments" type="commentsType" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="library" type="libraryType">
		<!-- Innerhalb eines Elements library
		     ist Element book eindeutig durch Unterelement isbn identifiziert. -->
		<xsd:key name="bookKey">
			<xsd:selector xpath="book"/>
			<xsd:field xpath="isbn"/>
		</xsd:key>
		<!-- Innerhalb eines Elements library
		     ist Element author eindeutig durch Unterelement name identifiziert. -->
		<xsd:key name="authorKey">
			<xsd:selector xpath="author"/>
			<xsd:field xpath="name"/>
		</xsd:key>
		<!-- Innerhalb eines Elements library
		     ist Element character eindeutig durch Unterelement name identifiziert. -->
		<xsd:key name="characterKey">
			<xsd:selector xpath="character"/>
			<xsd:field xpath="name"/>
		</xsd:key>
        <!-- Referenzielle Integrität: Jedes Textinhalt eines Elements author innerhalb von book
             bezieht sich auf einen Eintrag in authorKey.-->
		<xsd:keyref refer="authorKey" name="bookAuthor2author">
			<xsd:selector xpath="book/author"/>
			<xsd:field xpath="."/>
		</xsd:keyref>
		<!-- Referenzielle Integrität: Jedes Textinhalt eines Elements character innerhalb von book
             bezieht sich auf einen Eintrag in characterKey.-->
		<xsd:keyref refer="characterKey" name="bookCharacter2character">
			<xsd:selector xpath="book/character"/>
			<xsd:field xpath="."/>
		</xsd:keyref>

		<!--
		Wie können wir ausdrücken, dass jeder characterRef ein Ziel hat?
		-->
	</xsd:element>
</xsd:schema>

=== rinnerfabian/unistuff/4. Semester/Publizieren/Material/schemaBeispielPeanuts/libraryNormalized.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-model href="libraryRefLocalIndex.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="libraryNormalized.xsd">
	<book>
		<isbn>0836217462</isbn>
		<title>Being a Dog Is a Full-Time Job</title>
		<author>Charles M. Schulz</author>
		<!-- Doppelter Autorenname nicht erlaubt.
		<author>Charles M. Schulz</author>
		-->
		<character>Peppermint Patty</character>
		<character>Snoopy</character>
		<character>Schroeder</character>
		<character>Lucy</character>
	</book>
	<book>
		<isbn>0805033106</isbn>
		<title>Peanuts Every Sunday </title>
		<author>Charles M. Schulz</author>
		<character>Snoopy</character>
		<character>Sally Brown</character>
		<!-- Doppelter Character-Wert nicht erlaubt.
		<character>Snoopy</character>
		-->
		<character>Linus</character>
		<character>Lucy</character>
	</book>

	<author>
		<name>Charles M. Schulz</name>
		<nickName>SPARKY</nickName>
		<born>November 26, 1922</born>
		<dead>February 12, 2000</dead>
	</author>
	
	<character>
		<name>Snoopy</name>
		<since>October 4, 1950</since>
		<qualification>extroverted beagle</qualification>
	</character>
	<character>
		<name>Sally Brown</name>
		<since>Aug, 22, 1960</since>
		<qualification>always looks for the easy way out</qualification>
	</character>
	<character>
		<name>Linus</name>
		<since>Sept. 19, 1952</since>
		<qualification>the intellectual of the gang</qualification>
	</character>
	<character>
		<name>Lucy</name>
		<since>March 3, 1952</since>
		<qualification>bossy, crabby and selfish</qualification>
	</character>
	<character>
		<name>Schroeder</name>
		<since>May 30, 1951</since>
		<qualification>brought classical music to the Peanuts strip</qualification>
	</character>
	<character>
		<name>Peppermint Patty</name>
		<since>Aug. 22, 1966</since>
		<qualification>bold, brash and tomboyish</qualification>
	</character>
	<!-- author und character können den gleichen Schlüsselwert haben (separate Indexe) -->
	<character>
		<name>Charles M. Schulz</name>
		<since>November 26, 1922</since>
		<qualification>creative</qualification>
	</character>
	
	<comments>
		<characterRef book="0805033106" character="Snoopy"/>
		<characterRef book="0805033106" character="Snoopy"/>
		<characterRef book="0836217462" character="Snoopy"/>
		<characterRef book="0836217462" character="Schroeder"/>
		<!-- Dangling references, Verstoß gegen referentielle Integrität (durch Schematron!)
		<characterRef book="0805033106" character="Haegar"/>
		<characterRef book="0805033106" character="Peppermint Patty"/>
		-->
	</comments>
</library>
